  - name : Configure Docker on EC2 Instances
    hosts: all
    become: true
    connection : ssh
    tasks : 
    - name: updating apt
      command : apt-get update
    
    - name: Install Python and PIP
      command: apt install -y python3-pip
   
    - name: Install Docker
      command: apt-get install docker.io -y
       
    - name : Start Docker Service
      command : systemctl start docker
      become : yes
      become_user : root

    - name: Deploy Docker Container
      command: docker run -itd -p 8085:8081 srija1991/financeme
